### ISSUE TITLE
Bounus points for opening a drawer

### ISSUE THREAD

**Issue by TomohiroOno33** [hsr-project/tmc_gazebo_task_evaluators#4]
Will the bonus points for opening a drawer be scored by the scoring system in the future?

**Comment by yosuke** [comment]
Sorry for the delay.
We have implemented this bonus and updated the docker image.

**Comment by TomohiroOno33** [comment]
Thank you very much.
We have confirmed that bonus points are scored in the new environment.

**Comment by TomohiroOno33** [comment]
Sometimes the robot opens all the drawers, but does not get the bonus points (like in this image).
Does this mean that the robot has to open more?

![drawer](https://user-images.githubusercontent.com/72919166/121890899-d1c20600-cd55-11eb-96fe-85956ee0d077.png)

**Comment by yosuke** [comment]
Yes, you have to pull out the drawer bit more.
The current implementation requires you to pull the drawer out at least for about half the length of the drawer.
Please let us know if you feel this is too difficult.

**Comment by TomohiroOno33** [comment]
I understood it clearly.
I think the difficulty level is appropriate for bonus points.
Thank you!
